declare const styles: {
    readonly wrapper: string;
    readonly card: string;
    readonly left: string;
    readonly right: string;
    readonly heading: string;
    readonly underline: string;
    readonly text: string;
    readonly contactList: string;
    readonly contactItem: string;
    readonly iconCircle: string;
    readonly itemTitle: string;
    readonly itemText: string;
    readonly socials: string;
    readonly socialLink: string;
    readonly form: string;
    readonly field: string;
    readonly fieldError: string;
    readonly fieldSuccess: string;
    readonly fieldLabel: string;
    readonly fieldInput: string;
    readonly fieldTextarea: string;
    readonly fieldButton: string;
    readonly fieldButtonDisabled: string;
    readonly checkboxField: string;
    readonly submitBtn: string;
    readonly link: string;
    readonly secure: string;
    readonly status: string;
};

export default styles; 